Update windows.yaml

diff --git a/.github/workflows/windows.yaml b/.github/workflows/windows.yaml
--- a/.github/workflows/windows.yaml
+++ b/.github/workflows/windows.yaml
@@ -14,7 +14,7 @@ jobs:
       MUMPS_SOLVERS: dmumps
       MUMPS_ROOT: ${{ github.workspace }}\mumps
       MUMPS_INC: ${{ github.workspace }}\mumps\include
-      MUMPS_LIB: ${{ github.workspace }}\mumps\lib
+      MUMPS_LIB: ${{ github.workflow }}\mumps\lib
 
     steps:
     - name: Setup MSYS2 with required packages
@@ -31,6 +31,7 @@ jobs:
           mingw-w64-x86_64-python
           mingw-w64-x86_64-python-pip
           mingw-w64-x86_64-python-numpy
+          mingw-w64-x86_64-python-scipy
           mingw-w64-x86_64-python-mpi4py
           mingw-w64-x86_64-msmpi
 
@@ -46,9 +47,10 @@ jobs:
     - name: Download and extract MUMPS
       shell: msys2 {0}
       run: |
-        curl -L -o mumps.tgz http://mumps.enseeiht.fr/MUMPS_5.6.2.tar.gz
+        curl -L -o mumps.tgz https://coin-or-tools.github.io/ThirdParty-Mumps/MUMPS_5.7.3.tar.gz
+        if [ $? -ne 0 ]; then echo "Download failed"; exit 1; fi
         tar -xf mumps.tgz
-        mv MUMPS_5.6.2 mumps
+        mv MUMPS_5.7.3 mumps
 
     - name: Configure and build MUMPS with MSMPI
       shell: msys2 {0}
